import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/providers/index";
import { Header } from "@/components/header/index";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import favicon from "@/assets/favicon.ico";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={`${favicon}`} />
      </head>
      <body
        className={`${inter.className} flex w-full justify-center min-h-screen bg-custom-grayOne`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
